### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [Chonim/beer-cart#1]
Hi @Chonim  I am a graphic artist and would like to design a logo to your project for free. If you are interested and will allow me, I will begin asap. Best regards! - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by Chonim** [comment]
Hi @Tobaloidee,

Thank you for your interest and proposal. I saw your steemit page and the logos look really awesome.

However, this project is just for a simple demo purpose and not going to be officially released.
But it will be much appreciated if I can get your help with some of my official projects in the future.
Thanks again I hope we can make something cool together in the near future.

Cheers,
Chiho
